steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/nav-processor", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/nav-processor"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "nav-processor"
      - "--image"
      - "gcr.io/$PROJECT_ID/nav-processor"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - >-
        ETPCAP2_FTP_HOST=${_ETPCAP2_FTP_HOST},
        ETPCAP2_FTP_USER=${_ETPCAP2_FTP_USER},
        ETPCAP2_FTP_PASSWORD=${_ETPCAP2_FTP_PASSWORD},
        HFMX_FTP_HOST=${_HFMX_FTP_HOST},
        HFMX_FTP_USER=${_HFMX_FTP_USER},
        HFMX_FTP_PASSWORD=${_HFMX_FTP_PASSWORD},
        IACAP_FTP_HOST=${_IACAP_FTP_HOST},
        IACAP_FTP_USER=${_IACAP_FTP_USER},
        IACAP_FTP_PASSWORD=${_IACAP_FTP_PASSWORD},
        CIX_FTP_HOST=${_CIX_FTP_HOST},
        CIX_FTP_USER=${_CIX_FTP_USER},
        CIX_FTP_PASSWORD=${_CIX_FTP_PASSWORD},
        DCXPD_FTP_HOST=${_DCXPD_FTP_HOST},
        DCXPD_FTP_USER=${_DCXPD_FTP_USER},
        DCXPD_FTP_PASSWORD=${_DCXPD_FTP_PASSWORD},
        SMTP_HOST=${_SMTP_HOST},
        SMTP_PORT=${_SMTP_PORT},
        SMTP_USER=${_SMTP_USER},
        SMTP_PASSWORD=${_SMTP_PASSWORD},
        SMTP_USE_TLS=${_SMTP_USE_TLS},
        GOOGLE_DRIVE_CREDENTIALS_PATH=${_GOOGLE_DRIVE_CREDENTIALS_PATH},
        DRIVE_OUTPUT_FOLDER_ID=${_DRIVE_OUTPUT_FOLDER_ID},
        DRIVE_INPUT_FOLDER_ID=${_DRIVE_INPUT_FOLDER_ID},
        API_KEY=${_API_KEY}

images:
  - "gcr.io/$PROJECT_ID/nav-processor"
