version: '3.8'
services:
  nav-processor:
    build: .
    ports:
      - "9080:9080"
    env_file:
      - .env.production
    volumes:
      # Mount output directory for persistence
      - ./output:/app/output
      # Mount persistent database volume
      - nav-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=9080
      - DATABASE_URL=sqlite:////app/data/nav_data.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  nav-data:
    # This creates a named volume that persists between container restarts
