"""add notes column to fee structures

Revision ID: b4226bb4ff73
Revises: add_nav_unique_constraint
Create Date: 2025-03-23 23:46:53.573228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4226bb4ff73'
down_revision: Union[str, None] = 'add_nav_unique_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_structures', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_structures', 'notes')
    # ### end Alembic commands ###
